---
k8s_cluster_endpoint_name: k8s-cluster.fzymgc.house
k8s_cluster_endpoint_ip: 10.255.254.6
k8s_cluster_sans:
  - k8s-cluster.fzymgc.house
  - 10.255.254.6
  - 192.168.20.140  # kube-vip VIP
  - 192.168.20.141
  - 192.168.20.142
  - 192.168.20.143
  - 192.168.20.144
  - 192.168.20.151
  - 192.168.20.152
  - 192.168.20.153
  - 192.168.20.154
k8s_context: fzymgc-house
k8s_user_name: fzymgc
