tpi_bmc_host: tpi-alpha-bmc

tpi_bmc_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'infrastructure/bmc/tpi-alpha', engine_mount_point='secret/fzymgc-house').secret.password }}"

machine_kind: rk1
machine_arch: arm64

host_group_name: tpi_alpha_hosts
