# SPDX-License-Identifier: MIT-0
# code: language=ansible
---
# handlers file for k3s-common

- name: Restart k3s
  ansible.builtin.systemd:
    name: "{{ 'k3s' if k3s_role | default('agent') == 'server' else 'k3s-agent' }}"
    state: restarted
  when: k3s_existing_install | default(false)
