---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mealie.fzymgc.house`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
    - match: Host(`mealie.k8s.fzymgc.house`)
      kind: Rule
      services:
        - name: mealie
          port: 9000
  tls:
    secretName: mealie-tls
