summary: ''
description: ''
lock: '!inline f/terraform/test_configuration.script.lock'
kind: script
schema:
  $schema: 'https://json-schema.org/draft/2020-12/schema'
  type: object
  properties: {}
  required: []
