apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcp-terraform

resources:
  - namespace.yaml
  - external-secrets.yaml
  - agent-pool.yaml

# Helm values will be referenced by ArgoCD application
