---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-events
  namespace: argo-events
spec:
  secretName: argo-events-tls
  issuerRef:
    name: fzymgc-house-issuer
    kind: ClusterIssuer
  dnsNames:
    - argo-events.fzymgc.house
    - argoevents.fzymgc.house
    - wh-events.fzymgc.house
  usages:
    - server auth
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argo-events
  namespace: argo-events
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`wh-events.fzymgc.house`) && PathPrefix(`/github-event`)
      kind: Rule
      services:
        - name: github-eventsource-svc
          port: 12000
    - match: Host(`argo-events.fzymgc.house`) && PathPrefix(`/github-event`)
      kind: Rule
      services:
        - name: github-eventsource-svc
          port: 12000
    - match: Host(`argoevents.fzymgc.house`) && PathPrefix(`/github-event`)
      kind: Rule
      services:
        - name: github-eventsource-svc
          port: 12000
  tls:
    secretName: argo-events-tls
