apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-events

resources:
  - github-app-fzymgc-house-creds.yaml
  - event-bus.yaml
  - github-event-source.yaml
  - ingress.yaml
  - rbac.yaml
