---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd-projects.yaml
  - ./fzymgc-certificates.yaml
  - ./longhorn-storage-classes.yaml
  - ./longhorn-volumesnapshots.yaml
  - ./argocd-repositories.yaml
