description: Discord bot token and channel for Terraform notifications
value:
  channel_id: '$var:g/all/discord_channel_id'
  token: '$var:g/all/discord_bot_token'
resource_type: c_discord_bot_token_configuration
