apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - grafana.yaml
  - grafana-certificate.yaml
  - grafana-admin-external-secret.yaml
  - grafana-oidc-creds.yaml
  - datasources
  - dashboards
