apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certificates.yaml
  - storageclass-postgres.yaml
  - users.yaml
  - users-windmill.yaml
  - postgres-cluster.yaml
  - backup.yaml
  - db-authentik.yaml
  - db-grafana.yaml
  - db-windmill.yaml
  - db-mealie.yaml
  - users-mealie.yaml
  - ingress-route.yaml
  - https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.6.0/manifest.yaml


