---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teleport
resources:
  - namespace.yaml
  - rbac.yaml
  - postgres-cluster.yaml
  - db-secrets.yaml
  - join-token-secret.yaml
  - certificate.yaml
  - oidc-secrets.yaml
  - oidc-connector.yaml
  - roles.yaml
