# SPDX-License-Identifier: MIT-0
# code: language=ansible
---
galaxy_info:
  author: fzymgc-house
  description: Deploy kube-vip for Kubernetes API endpoint high availability
  license: MIT-0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - noble

dependencies: []

# Required collections (versions in ansible/requirements.yml)
collections:
  - ansible.utils
